# -*- coding: utf-8 -*-
"""Hinglish

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X9n6NE8wE7j56NaPRIVOBhheQ52iEyOY
"""

pip install transformers[sentencepiece]

pip install transformers

from transformers import pipeline

# Create a translation pipeline for English to Hindi
translator = pipeline("translation", model="Helsinki-NLP/opus-mt-en-hi")

""" **Statement1**"""

# Get input text from the user
english_text = input("Enter the English text to translate into Hinglish: ")

# Translate to Hinglish (English-Hindi mixed)
hinglish_translation = translator(english_text, max_length=100)[0]["translation_text"]

# Print the translated text
print("\nHinglish Translation:")
print(hinglish_translation)

"""**Statement2**"""

# Get input text from the user
english_text = input("Enter the English text to translate into Hinglish: ")

# Translate to Hinglish (English-Hindi mixed)
hinglish_translation = translator(english_text, max_length=100)[0]["translation_text"]

# Print the translated text
print("\nHinglish Translation:")
print(hinglish_translation)

"""**Statement3**"""

# Get input text from the user
english_text = input("Enter the English text to translate into Hinglish: ")

# Translate to Hinglish (English-Hindi mixed)
hinglish_translation = translator(english_text, max_length=100)[0]["translation_text"]

# Print the translated text
print("\nHinglish Translation:")
print(hinglish_translation)